import type { NextPage } from 'next';
import Head from 'next/head';
import homeDataJson from '../../data/homes.json';
import { HomeCard } from '../components/HomeCard/HomeCard';

const Home: NextPage = () => {
	const homeData = homeDataJson;

	return (
		<div className='bg-slate-200 flex-1 h-screen'>
			<Head>
				<title>Angelo</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='flex flex-row flex-wrap w-full'>
				{homeData.map((home, index) => {
					return <HomeCard key={index} data={home} />;
				})}
			</div>
		</div>
	);
};

export default Home;
